CREATE TABLE "continent" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "code" varchar
);

CREATE TABLE "country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar,
  "code" varchar,
  "continent_id" int
);

CREATE TABLE "departament" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "description" varchar,
  "country_id" int
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "description" varchar,
  "departament_id" int
);

CREATE TABLE "neighborhood" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "description" varchar,
  "location_id" int
);

CREATE TABLE "status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "location" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "description" varchar,
  "departament_id" int
);

CREATE TABLE "regional" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "department_id" int
);

CREATE TABLE "centro_formacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "regional_id" int,
  "city_id" int
);

CREATE TABLE "sede" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "neighborhood_id" int,
  "centro_formacion_id" int
);

CREATE TABLE "person" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_document" varchar,
  "document" varchar,
  "firts_name" varchar,
  "second_name" vaechar,
  "lasth_name" varchar,
  "second_surname" varchar,
  "email" varchar,
  "phone" varchar,
  "date_of_birth" varchar,
  "gender" varchar,
  "adress" varchar
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "pasword" varchar,
  "role_id" int,
  "person_id" int
);

CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "status_role" bool
);

CREATE TABLE "view" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar,
  "route" varchar,
  "code" integer,
  "view_id" int
);

CREATE TABLE "role_view" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Role_id" int,
  "view_id" int
);

CREATE TABLE "user_role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "rol_id" int
);

CREATE TABLE "module" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "route" varchar,
  "icon" varchar
);

CREATE TABLE "instructor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_role_id" int,
  "cargo_id" int
);

CREATE TABLE "aprendiz" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_role_id" int,
  "ficha_id" int,
  "ambiente_id" enum
);

CREATE TABLE "coordinador" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "user_role_id" int,
  "cargo_id" int
);

CREATE TABLE "personalAdministrativo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "user_role_id" int,
  "cargo_id" int
);

CREATE TABLE "gestorLinea" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "user_role_id" int,
  "cargo_id" int
);

CREATE TABLE "contratacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "user_role_id" int,
  "cargo_id" int
);

CREATE TABLE "ficha" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_ficha" varchar,
  "programa_formativo" enum,
  "coordinador_id" int
);

CREATE TABLE "ambiente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "ubicacion" varchar,
  "personal_administrativo_id" int
);

CREATE TABLE "competencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar
);

CREATE TABLE "fase" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar,
  "calendario_id" int
);

CREATE TABLE "calendario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_inicio" date,
  "fecha_fin" date
);

CREATE TABLE "pqrs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text,
  "fecha" date,
  "aprendiz_id" int
);

CREATE TABLE "consolidadoSemanal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_id" int,
  "semana" int,
  "descripcion" text
);

CREATE TABLE "consolidadoMensual" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_id" int,
  "mes" int,
  "descripcion" text
);

CREATE TABLE "periodo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar,
  "fecha_inicio" date,
  "fecha_fin" date
);

CREATE TABLE "jornada" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar,
  "hora_inicio" time,
  "hora_fin" time
);

CREATE TABLE "materia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "competencia_id" int
);

CREATE TABLE "resultadosAprendizaje" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text,
  "materia_id" int
);

CREATE TABLE "reporte" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text,
  "fecha" date,
  "ficha_id" int
);

CREATE TABLE "notificacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text,
  "fecha" date,
  "aprendiz_id" int
);

CREATE TABLE "instructor_ficha" (
  "instructor_id" int,
  "ficha_id" int
);

CREATE TABLE "ficha_competencia" (
  "ficha_id" int,
  "competencia_id" int
);

CREATE TABLE "instructor_materia" (
  "instructor_id" int,
  "materia_id" int
);

CREATE TABLE "horario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ambiente_id" int,
  "ficha_id" int,
  "materia_id" int,
  "jornada_id" int,
  "dia_semana" enum
);

CREATE TABLE "cargo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

ALTER TABLE "country" ADD FOREIGN KEY ("continent_id") REFERENCES "continent" ("id");

ALTER TABLE "departament" ADD FOREIGN KEY ("country_id") REFERENCES "country" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("departament_id") REFERENCES "departament" ("id");

ALTER TABLE "neighborhood" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "location" ADD FOREIGN KEY ("departament_id") REFERENCES "departament" ("id");

ALTER TABLE "regional" ADD FOREIGN KEY ("department_id") REFERENCES "departament" ("id");

ALTER TABLE "centro_formacion" ADD FOREIGN KEY ("regional_id") REFERENCES "regional" ("id");

ALTER TABLE "centro_formacion" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "sede" ADD FOREIGN KEY ("neighborhood_id") REFERENCES "neighborhood" ("id");

ALTER TABLE "sede" ADD FOREIGN KEY ("centro_formacion_id") REFERENCES "centro_formacion" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("id");

ALTER TABLE "view" ADD FOREIGN KEY ("view_id") REFERENCES "module" ("id");

ALTER TABLE "role_view" ADD FOREIGN KEY ("Role_id") REFERENCES "role" ("id");

ALTER TABLE "role_view" ADD FOREIGN KEY ("view_id") REFERENCES "view" ("id");

ALTER TABLE "user_role" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_role" ADD FOREIGN KEY ("rol_id") REFERENCES "role" ("id");

ALTER TABLE "instructor" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "instructor" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "aprendiz" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "aprendiz" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "coordinador" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "coordinador" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "personalAdministrativo" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "personalAdministrativo" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "gestorLinea" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "gestorLinea" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "contratacion" ADD FOREIGN KEY ("user_role_id") REFERENCES "user_role" ("id");

ALTER TABLE "contratacion" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "ficha" ADD FOREIGN KEY ("coordinador_id") REFERENCES "coordinador" ("id");

ALTER TABLE "ambiente" ADD FOREIGN KEY ("personal_administrativo_id") REFERENCES "personalAdministrativo" ("id");

ALTER TABLE "fase" ADD FOREIGN KEY ("calendario_id") REFERENCES "calendario" ("id");

ALTER TABLE "pqrs" ADD FOREIGN KEY ("aprendiz_id") REFERENCES "aprendiz" ("id");

ALTER TABLE "consolidadoSemanal" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "consolidadoMensual" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "materia" ADD FOREIGN KEY ("competencia_id") REFERENCES "competencia" ("id");

ALTER TABLE "resultadosAprendizaje" ADD FOREIGN KEY ("materia_id") REFERENCES "materia" ("id");

ALTER TABLE "reporte" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "notificacion" ADD FOREIGN KEY ("aprendiz_id") REFERENCES "aprendiz" ("id");

ALTER TABLE "instructor_ficha" ADD FOREIGN KEY ("instructor_id") REFERENCES "instructor" ("id");

ALTER TABLE "instructor_ficha" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "ficha_competencia" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "ficha_competencia" ADD FOREIGN KEY ("competencia_id") REFERENCES "competencia" ("id");

ALTER TABLE "instructor_materia" ADD FOREIGN KEY ("instructor_id") REFERENCES "instructor" ("id");

ALTER TABLE "instructor_materia" ADD FOREIGN KEY ("materia_id") REFERENCES "materia" ("id");

ALTER TABLE "horario" ADD FOREIGN KEY ("ambiente_id") REFERENCES "ambiente" ("id");

ALTER TABLE "horario" ADD FOREIGN KEY ("ficha_id") REFERENCES "ficha" ("id");

ALTER TABLE "horario" ADD FOREIGN KEY ("materia_id") REFERENCES "materia" ("id");

ALTER TABLE "horario" ADD FOREIGN KEY ("jornada_id") REFERENCES "jornada" ("id");
